Fixed bug

diff --git a/.github/workflows/on-pull-request.yml b/.github/workflows/on-pull-request.yml
--- a/.github/workflows/on-pull-request.yml
+++ b/.github/workflows/on-pull-request.yml
@@ -28,13 +28,15 @@ jobs:
       - name: Run Tests
         run: |
           ./mvnw test
+
+
       # Adjust this command based on your project's test execution command
 
-      - name: Check Test Results
-        run: |
-          if [ -f target/surefire-reports/TEST-*.xml ]; then
-            echo "Tests passed"
-          else
-            echo "Tests failed"
-            exit 1
-          fi
+#      - name: Check Test Results
+#        run: |
+#          if [ -f target/surefire-reports/TEST-*.xml ]; then
+#            echo "Tests passed"
+#          else
+#            echo "Tests failed"
+#            exit 1
+#          fi
